// Seed content only. In connected mode the API/database is the source of truth.
export const categories = [
  {
    slug: "women",
    name: "Women's Salon & Spa",
    image: "category-women.jpeg",
    short: "Salon for women",
  },
  {
    slug: "men",
    name: "Men's Salon & Massage",
    image: "category-men.jpeg",
    short: "Salon for men",
  },
  {
    slug: "cleaning",
    name: "Cleaning & Pest Control",
    image: "category-cleaning.jpeg",
    short: "Cleaning essentials",
  },
  {
    slug: "appliance",
    name: "AC & Appliance Repair",
    image: "category-appliance.jpeg",
    short: "Appliance repair & service",
  },
  {
    slug: "painting",
    name: "Home Painting & Upgrade",
    image: "category-painting.jpeg",
    short: "Refresh your home",
  },
  {
    slug: "repairs",
    name: "Electrician, Plumber & Carpenter",
    image: "category-repairs.jpeg",
    short: "Home repair & installation",
  },
];
const items = [
  [
    "ac-service",
    "Foam-jet AC service",
    "appliance",
    649,
    60,
    "service-ac-foam.jpeg",
    "4.75",
    "2.9M",
    "Deep cleaning for better cooling. Includes indoor unit, filters and outdoor unit cleaning.",
  ],
  [
    "haircut",
    "Haircut for men",
    "men",
    259,
    40,
    "service-haircut.jpeg",
    "4.86",
    "486K",
    "A professional haircut at home, with a consultation, styling and clean-up.",
  ],
  [
    "home-cleaning",
    "Full home deep cleaning",
    "cleaning",
    3499,
    240,
    "service-home-cleaning.jpeg",
    "4.79",
    "878K",
    "A detailed clean of your living spaces, kitchen and bathrooms using professional equipment.",
  ],
  [
    "ac-repair",
    "AC repair",
    "appliance",
    299,
    45,
    "service-ac-repair.jpeg",
    "4.73",
    "865K",
    "Diagnosis of cooling, noise and leakage issues. Spare parts and repairs quoted separately.",
  ],
  [
    "pedicure",
    "Crystal rose pedicure",
    "women",
    759,
    60,
    "service-pedicure.jpeg",
    "4.83",
    "344K",
    "Foot soak, nail care, gentle exfoliation and a relaxing foot massage.",
  ],
  [
    "carpenter",
    "Book a carpenter",
    "repairs",
    99,
    30,
    "service-carpenter.jpeg",
    "4.66",
    "191K",
    "Expert inspection for furniture and fittings. Final repair cost provided after inspection.",
  ],
  [
    "waxing",
    "Roll-on waxing",
    "women",
    899,
    60,
    "service-waxing.jpeg",
    "4.86",
    "261K",
    "Full arms, legs and underarms with single-use supplies and a trained professional.",
  ],
  [
    "plumber",
    "Plumber consultation",
    "repairs",
    49,
    30,
    "service-plumber.jpeg",
    "4.74",
    "214K",
    "Get help with leaking taps, blocked drains and bathroom fittings. Repairs quoted separately.",
  ],
  [
    "electrician",
    "Electrician consultation",
    "repairs",
    49,
    30,
    "service-electrician.jpeg",
    "4.75",
    "176K",
    "Diagnosis for switches, lights and fans. Parts and additional work charged after approval.",
  ],
  [
    "painting",
    "Full home painting",
    "painting",
    499,
    60,
    "service-painting.jpeg",
    "4.80",
    "12K",
    "An at-home consultation, wall measurement and detailed painting estimate. Consultation fee only.",
  ],
  [
    "bathroom-cleaning",
    "Bathroom deep cleaning",
    "cleaning",
    499,
    75,
    "service-home-cleaning.jpeg",
    "4.81",
    "124K",
    "Descaling tiles and fixtures, cleaning the toilet, sink, floor and accessible surfaces.",
  ],
  [
    "wall-panels",
    "Wall panel consultation",
    "painting",
    299,
    45,
    "wall-panels.jpeg",
    "4.80",
    "18K",
    "Discuss wall finishes, measurements and installation options. Materials and installation quoted separately.",
  ],
  [
    "purifier",
    "Water purifier service",
    "appliance",
    299,
    45,
    "purifier-service.jpeg",
    "4.80",
    "319K",
    "Professional inspection and servicing of your water purifier. Replacement filters quoted separately.",
  ],
  [
    "massage",
    "Relaxing head massage",
    "men",
    399,
    30,
    "service-haircut.jpeg",
    "4.82",
    "48K",
    "Unwind with a gentle head, neck and shoulder massage in the comfort of your home.",
  ],
];
export const services = items.map(
  ([
    slug,
    name,
    category,
    price,
    duration,
    image,
    rating,
    reviews,
    description,
  ]) => ({
    slug,
    name,
    category,
    price,
    duration,
    image,
    rating,
    reviews,
    description,
    active: true,
    includes: [
      "Trained and verified professional",
      "Professional equipment and supplies",
      "Clean-up after the service",
    ],
  }),
);
export const cities = [
  "Delhi NCR",
  "Lucknow",
  "Mumbai",
  "Bengaluru",
  "Hyderabad",
  "Pune",
  "Chennai",
  "Kolkata",
  "Kanpur",
];
export const slots = ["09:00", "11:00", "13:00", "15:00", "17:00"];
